package fyi.blep.ui.screens

// Generated by web/scripts/stitch-dog-sprites.mjs — do not edit.
// transition[fromClip.ordinal][toClip.ordinal][fromFrame] = matching entry frame in toClip.
internal object DogFrames {
    val transition: Array<Array<IntArray>> = arrayOf(
        arrayOf(intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23), intArrayOf(1, 3, 1, 3, 3, 3, 1, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 1, 8, 10, 20, 18), intArrayOf(16, 17, 18, 19, 2, 2, 18, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 23, 23, 1, 1, 1, 1), intArrayOf(0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 3, 1, 1, 3, 3, 3, 1, 0, 0, 5, 5, 4, 4)),
        arrayOf(intArrayOf(1, 2, 2, 3, 0, 4, 21, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21), intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23), intArrayOf(8, 9, 10, 9, 14, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), intArrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)),
        arrayOf(intArrayOf(7, 21, 4, 8, 2, 2, 2, 8, 1, 0, 2, 0, 0, 1, 3, 1, 0, 1, 2, 1, 0, 1, 0, 1), intArrayOf(20, 22, 4, 0, 2, 1, 2, 2, 0, 3, 2, 3, 1, 0, 3, 0, 1, 3, 1, 3, 4, 3, 4, 3), intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23), intArrayOf(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)),
        arrayOf(intArrayOf(19, 14, 16, 16, 22, 22, 22, 19, 19, 19, 22, 7), intArrayOf(16, 0, 0, 0, 22, 8, 20, 0, 6, 22, 20, 12), intArrayOf(20, 3, 3, 3, 19, 15, 1, 23, 19, 21, 0, 0), intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11))
    )
}
