package fyi.blep.ui.screens

// Generated by web/scripts/stitch-dog-sprites.mjs — do not edit.
internal object DogFrames {
    /** All per-clip arrays are indexed by DogClip.ordinal (clip order in dog-frames.json). */
    /** Frame count per clip, after the stitcher's loop-trim. */
    val frameCount: IntArray = intArrayOf(24, 10, 20, 24)

    /** Playback frames-per-second per clip. */
    val fps: IntArray = intArrayOf(12, 12, 12, 12)

    /** Whether each clip loops (true) or plays once and holds (false). */
    val loop: BooleanArray = booleanArrayOf(true, true, true, false)

    /** Whether each clip plays in reverse. */
    val reverse: BooleanArray = booleanArrayOf(true, true, true, false)

    /** transition[fromClip.ordinal][toClip.ordinal][fromFrame] = matching entry frame in toClip. */
    val transition: Array<Array<IntArray>> = arrayOf(
        arrayOf(intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23), intArrayOf(0, 0, 0, 2, 0, 0, 2, 0, 2, 1, 0, 2, 2, 2, 0, 0, 0, 1, 3, 3, 2, 0, 3, 0), intArrayOf(3, 8, 8, 8, 10, 8, 10, 8, 10, 7, 8, 7, 10, 10, 8, 8, 8, 4, 10, 9, 10, 8, 4, 4), intArrayOf(4, 4, 18, 4, 4, 4, 18, 4, 4, 18, 18, 18, 4, 5, 4, 4, 18, 18, 9, 18, 18, 18, 18, 18)),
        arrayOf(intArrayOf(16, 17, 12, 19, 18, 18, 18, 7, 7, 7), intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), intArrayOf(8, 4, 10, 9, 2, 2, 1, 1, 1, 1), intArrayOf(18, 18, 18, 18, 9, 9, 21, 21, 21, 21)),
        arrayOf(intArrayOf(18, 18, 18, 0, 17, 17, 20, 17, 16, 17, 18, 18, 17, 18, 19, 16, 18, 23, 17, 17), intArrayOf(9, 8, 4, 0, 1, 1, 1, 1, 0, 3, 2, 3, 3, 0, 3, 0, 3, 3, 1, 3), intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19), intArrayOf(23, 21, 9, 5, 18, 18, 18, 18, 18, 18, 4, 9, 18, 18, 18, 18, 18, 18, 18, 18)),
        arrayOf(intArrayOf(0, 0, 0, 0, 18, 13, 0, 0, 21, 18, 0, 0, 0, 0, 0, 0, 1, 0, 22, 23, 21, 7, 18, 22), intArrayOf(0, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 8, 0, 0, 9, 9, 0, 0, 0, 0, 8, 8, 8), intArrayOf(3, 3, 3, 3, 8, 3, 3, 3, 3, 15, 3, 3, 0, 3, 3, 3, 3, 3, 17, 19, 15, 1, 1, 1), intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23))
    )
}
