#!/usr/bin/env bash
# Regenerate the Wear app's localized strings from the phone's Compose-resources
# catalog. The watch shows a small subset of the phone's strings (guidance titles,
# turn-by-turn line, distance, floor hints, "Connected"); rather than translate
# them twice, we copy those exact keys/values out of composeApp's strings.xml into
# wearApp's Android res/ so both stay in sync. Run after editing the phone catalog.
#
#   tools/wear-strings.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SX="$ROOT/app/composeApp/src/commonMain/composeResources"
WRES="$ROOT/app/wearApp/src/main/res"

# The keys the watch UI renders (see WearApp.kt). app_name stays wear-local.
#
# KEEP THIS IN SYNC. Every string the watch resolves must be listed here: the
# generator *overwrites* wearApp's res/, so a key the watch uses but this list omits
# is silently deleted on the next run and the build breaks on R.string.<key>. (That
# is exactly what happened to the settings/tether/notification keys below, which had
# to be recovered by hand.) After adding a key here, run this script and build
# :wearApp — do not hand-edit the generated files.
KEYS="status_connected nearby_count \
cue_calibrate_title cue_sweep_start_title cue_sweep_warmer_title cue_sweep_colder_title \
cue_sweep_flat_title cue_walk_warmer_title cue_walk_colder_title cue_walk_flat_title \
cue_walk_overshoot_title cue_walk_found_title cue_reorient_title cue_pinpoint_title \
cue_pinpoint_lost_title cue_complete_title \
line_facing_signal line_turn_to_signal line_ahead_warmer line_turn_warmer line_target \
turn_ahead turn_right turn_left line_distance_almost line_distance_m \
distance_almost_on_it distance_away \
tracking_right_here dbm \
noti_channel_alert noti_alert_title noti_alert_text noti_alert_named \
noti_channel_tether noti_channel_tether_info \
noti_tether_left_title noti_tether_left_text noti_tether_back_title noti_tether_back_text \
noti_phone_left_title noti_phone_left_text noti_phone_back_text \
settings_title settings_phone_tether_title settings_phone_tether_desc \
settings_sync_favorites settings_tether_title \
detail_tether detail_tethered action_done discovery_empty_title \
floor_up_one floor_up_many floor_down_one floor_down_many"

gen() { # srcdir destdir
  local src="$1/strings.xml" dest="$2/strings.xml"
  [ -f "$src" ] || { echo "MISSING $src" >&2; return 1; }
  mkdir -p "$2"
  {
    echo '<?xml version="1.0" encoding="utf-8"?>'
    echo '<!-- Generated by tools/wear-strings.sh from composeApp/…/composeResources. Do not edit by hand. -->'
    echo '<resources>'
    echo '    <string name="app_name">blep</string>'
    # composeResources use plain apostrophes; Android AAPT needs them escaped (\').
    for k in $KEYS; do grep -h "name=\"$k\"" "$src" | sed "s/'/\\\\'/g"; done
    echo '</resources>'
  } > "$dest"
  echo "wrote $dest ($(grep -c '<string ' "$dest") strings)"
}

gen "$SX/values" "$WRES/values"
for d in "$SX"/values-*; do gen "$d" "$WRES/$(basename "$d")"; done
echo "✓ wear strings regenerated for $(( $(ls -d "$SX"/values-* | wc -l) + 1 )) locales"
